name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        tf-version: ['tf208-cpu', 'tf216-cpu', 'tf217-cpu', 'tf218-cpu']
        python-version: ['3.10', '3.12']
        os: [ubuntu-latest, macos-latest]
        exclude:
          # tf208,은 Python 3.12와 호환되지 않음
          - tf-version: 'tf208-cpu'
            os: macos-latest
            python-version: ['3.10', '3.12']
          - tf-version: 'tf208-cpu'
            os: ubuntu-latest
            python-version: '3.12'
          - tf-version: 'tf216-cpu'
            python-version: '3.10'
          - tf-version: 'tf217-cpu'
            python-version: '3.10'
          - tf-version: 'tf218-cpu'
            python-version: '3.10'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev --extra ${{ matrix.tf-version }}

      - name: Format
        run: |
          uvx ruff format

      - name: Lint
        run: |
          uvx ruff check --fix --exit-non-zero-on-fix .

      - name: Lint GitHub Actions
        uses: eifinger/actionlint-action@v1

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        tf-version: ['tf208-cpu', 'tf216-cpu', 'tf217-cpu', 'tf218-cpu']
        python-version: ['3.10', '3.12']
        os: [ubuntu-latest, macos-latest]
        exclude:
          # tf208-cpu와 python 3.12 조합 제외
          - tf-version: 'tf208-cpu'
            python-version: '3.12'
            os: macos-latest
          # tf216-cpu, tf217-cpu, tf218-cpu와 python 3.10 조합 제외
          - tf-version: 'tf216-cpu'
            python-version: '3.10'
          - tf-version: 'tf217-cpu'
            python-version: '3.10'
          - tf-version: 'tf218-cpu'
            python-version: '3.10'
        include:
          # tf208-cpu는 python 3.10, os ubuntu-latest에서만 실행
          - tf-version: 'tf208-cpu'
            python-version: '3.10'
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --dev --extra ${{ matrix.tf-version }}

      - name: Run tests
        run: |
          uv run coverage run -m pytest src/tests/
          uv run coverage run -m pytest src/tests/
